name: Code Field action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2.3.0

      - name: Install dependencies
        run: flutter pub get

      - name: Build web example
        working-directory: ./example
        run: flutter build web

  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2.3.0

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze      

      
